import random
import pandas as pd

# Word lists for variety
adjectives = ["Spicy", "Savory", "Sweet", "Tangy", "Zesty", "Juicy", "Crispy", "Crunchy", "Tender", "Smoky",
              "Salty", "Buttery", "Creamy", "Nutty", "Earthy", "Fruity", "Herbal", "Peppery", "Sugary", "Golden",
              "Toasted", "Caramelized", "Roasted", "Grilled", "Baked", "Steamed", "Pickled", "Fermented", "Fresh",
              "Organic",
              "Natural", "Wholesome", "Healthy", "Hearty", "Rich", "Velvety", "Silky", "Smooth", "Fluffy", "Airy",
              "Chewy", "Sticky", "Gooey", "Moist", "Dry", "Cured", "Marinated", "Seasoned", "Balanced", "Bold",
              "Delicate", "Elegant", "Fiery", "Hot", "Cold", "Frozen", "Chilled", "Iced", "Warm", "Comforting",
              "Homemade", "Rustic", "Artisan", "Crafted", "Exotic", "Tropical", "Citrusy", "Berry", "Leafy", "Rooted",
              "Appetizing", "Tasty", "Flavorful", "Delectable", "Mouthwatering", "Palatable", "Satisfying", "Gourmet",
              "Decadent", "Luxurious",
              "Premium", "Classic", "Traditional", "Modern", "Fusion", "Global", "Local", "Seasonal", "Farm-fresh",
              "Garden",
              "Wild", "Foraged", "Sun-dried", "Charred", "Smoked", "Burnt", "Golden-brown", "Amber", "Ruby", "Emerald",
              "Sapphire", "Chocolatey", "Vanilla", "Cinnamon", "Spiced", "Peppered", "Garlicky", "Oniony", "Cheesy",
              "Milky",
              "Eggy", "Meaty", "Fishy", "Sea-salted", "Umami", "Sharp", "Piquant", "Robust", "Full-bodied", "Light",
              "Heavy", "Dense", "Thick", "Thin", "Runny", "Saucy", "Brothy", "Soupy", "Oily", "Greasy",
              "Fatty", "Lean", "Protein-rich", "Carb-heavy", "Gluten-free", "Vegan", "Vegetarian", "Plant-based", "Raw",
              "Cooked",
              "Half-baked", "Golden-crusted", "Flaky", "Layered", "Stuffed", "Filled", "Rolled", "Wrapped", "Dipped",
              "Drizzled",
              "Sprinkled", "Powdered", "Dusty", "Glazed", "Frosted", "Iced", "Candied", "Honeyed", "Maple", "Molten",
              "Syrupy", "Sticky-sweet", "Sugared", "Complex", "Simple", "Minimalist", "Colorful", "Vibrant", "Bright",
              "Dark",
              "Pale", "Rosy", "Crimson", "Scarlet", "Ivory", "Browned", "Charcoal", "Smoldering", "Refreshing",
              "Cooling",
              "Hydrating", "Quenching", "Invigorating", "Energizing", "Soulful", "Festive", "Celebratory",
              "Party-ready", "Picnic-style", "Street-food",
              "Casual", "Upscale", "Affordable", "Budget-friendly", "Family-style", "Kid-friendly", "Playful", "Fun",
              "Cheerful", "Joyful",
              "Cozy", "Warm-hearted", "Inviting", "Welcoming", "Generous", "Abundant", "Plentiful", "Overflowing",
              "Bountiful", "Lavish",
              "Sumptuous", "Grand", "Magnificent", "Delicious", "Scrumptious", "Yummy", "Lip-smacking",
              "Finger-licking", "Snackable", "Portable",
              "Handheld", "Messy", "Neat", "Elegant", "Sophisticated", "Refined", "Rustic", "Homely", "Comfort-food",
              "Soulful",
              "Seasoned", "Zingy", "Fiery-red", "Golden", "Amber-toned", "Rosy-pink", "Chocolate-brown",
              "Vanilla-white", "Berry-bright", "Citrus-fresh",
              "Nutty-rich", "Herbal-green", "Leafy-fresh", "Rooty", "Grainy", "Seedy", "Toasty", "Buttery-soft",
              "Cream-filled", "Egg-rich",
              "Cheese-loaded", "Meat-packed", "Fish-fresh", "Sea-bright", "Oceanic", "Briny", "Pickled-sharp",
              "Fermented-bold", "Saucy-rich", "Brothy-light",
              "Soupy-thick", "Oily-rich", "Greasy-heavy", "Lean-clean", "Protein-packed", "Carb-loaded", "Gluten-light",
              "Vegan-friendly", "Vegetarian-classic", "Plant-rich",
              "Raw-fresh", "Cooked-hot", "Half-done", "Crusted", "Flaky-light", "Layered-rich", "Stuffed-full",
              "Wrapped-tight", "Dipped-sweet", "Drizzled-fine",
              "Sprinkled-light", "Powdered-soft", "Dusty-sweet", "Glazed-shiny", "Frosted-cool", "Iced-fresh",
              "Candied-sugar", "Honey-sweet", "Maple-rich", "Molten-hot",
              "Syrupy-thick", "Sugared-light", "Complex-flavor", "Simple-taste", "Minimalist-style", "Colorful-plate",
              "Vibrant-dish", "Bright-fresh", "Dark-rich", "Pale-soft",
              "Rosy-fresh", "Crimson-bold", "Scarlet-hot", "Ivory-light", "Browned-rich", "Charcoal-dark",
              "Smoldering-hot", "Refreshing-cool", "Cooling-fresh", "Hydrating-light",
              "Quenching-fresh", "Invigorating-strong", "Energizing-bright", "Soulful-rich", "Festive-bright",
              "Celebratory-joyful", "Party-style", "Picnic-ready", "Street-classic", "Casual-fresh",
              "Upscale-rich", "Affordable-light", "Budget-classic", "Family-style", "Kid-happy", "Playful-fun",
              "Cheerful-bright", "Joyful-rich", "Cozy-warm", "Inviting-fresh",
              "Welcoming-bright", "Generous-rich", "Abundant-full", "Plentiful-rich", "Overflowing-bright",
              "Bountiful-rich", "Lavish-full", "Sumptuous-rich", "Grand-classic", "Magnificent-rich"
              ]
nouns = ["Spicy", "Savory", "Sweet", "Tangy", "Zesty", "Juicy", "Crispy", "Crunchy", "Tender", "Smoky",
         "Salty", "Buttery", "Creamy", "Nutty", "Earthy", "Fruity", "Herbal", "Peppery", "Sugary", "Golden",
         "Toasted", "Caramelized", "Roasted", "Grilled", "Baked", "Steamed", "Pickled", "Fermented", "Fresh", "Organic",
         "Natural", "Wholesome", "Healthy", "Hearty", "Rich", "Velvety", "Silky", "Smooth", "Fluffy", "Airy",
         "Chewy", "Sticky", "Gooey", "Moist", "Dry", "Cured", "Marinated", "Seasoned", "Balanced", "Bold",
         "Delicate", "Elegant", "Fiery", "Hot", "Cold", "Frozen", "Chilled", "Iced", "Warm", "Comforting",
         "Homemade", "Rustic", "Artisan", "Crafted", "Exotic", "Tropical", "Citrusy", "Berry", "Leafy", "Rooted",
         "Appetizing", "Tasty", "Flavorful", "Delectable", "Mouthwatering", "Palatable", "Satisfying", "Gourmet",
         "Decadent", "Luxurious",
         "Premium", "Classic", "Traditional", "Modern", "Fusion", "Global", "Local", "Seasonal", "Farm-fresh", "Garden",
         "Wild", "Foraged", "Sun-dried", "Charred", "Smoked", "Burnt", "Golden-brown", "Amber", "Ruby", "Emerald",
         "Sapphire", "Chocolatey", "Vanilla", "Cinnamon", "Spiced", "Peppered", "Garlicky", "Oniony", "Cheesy", "Milky",
         "Eggy", "Meaty", "Fishy", "Sea-salted", "Umami", "Sharp", "Piquant", "Robust", "Full-bodied", "Light",
         "Heavy", "Dense", "Thick", "Thin", "Runny", "Saucy", "Brothy", "Soupy", "Oily", "Greasy",
         "Fatty", "Lean", "Protein-rich", "Carb-heavy", "Gluten-free", "Vegan", "Vegetarian", "Plant-based", "Raw",
         "Cooked",
         "Half-baked", "Golden-crusted", "Flaky", "Layered", "Stuffed", "Filled", "Rolled", "Wrapped", "Dipped",
         "Drizzled",
         "Sprinkled", "Powdered", "Dusty", "Glazed", "Frosted", "Iced", "Candied", "Honeyed", "Maple", "Molten",
         "Syrupy", "Sticky-sweet", "Sugared", "Complex", "Simple", "Minimalist", "Colorful", "Vibrant", "Bright",
         "Dark",
         "Pale", "Rosy", "Crimson", "Scarlet", "Ivory", "Browned", "Charcoal", "Smoldering", "Refreshing", "Cooling",
         "Hydrating", "Quenching", "Invigorating", "Energizing", "Soulful", "Festive", "Celebratory", "Party-ready",
         "Picnic-style", "Street-food",
         "Casual", "Upscale", "Affordable", "Budget-friendly", "Family-style", "Kid-friendly", "Playful", "Fun",
         "Cheerful", "Joyful",
         "Cozy", "Warm-hearted", "Inviting", "Welcoming", "Generous", "Abundant", "Plentiful", "Overflowing",
         "Bountiful", "Lavish",
         "Sumptuous", "Grand", "Magnificent", "Delicious", "Scrumptious", "Yummy", "Lip-smacking", "Finger-licking",
         "Snackable", "Portable",
         "Handheld", "Messy", "Neat", "Elegant", "Sophisticated", "Refined", "Rustic", "Homely", "Comfort-food",
         "Soulful",
         "Seasoned", "Zingy", "Fiery-red", "Golden", "Amber-toned", "Rosy-pink", "Chocolate-brown", "Vanilla-white",
         "Berry-bright", "Citrus-fresh",
         "Nutty-rich", "Herbal-green", "Leafy-fresh", "Rooty", "Grainy", "Seedy", "Toasty", "Buttery-soft",
         "Cream-filled", "Egg-rich",
         "Cheese-loaded", "Meat-packed", "Fish-fresh", "Sea-bright", "Oceanic", "Briny", "Pickled-sharp",
         "Fermented-bold", "Saucy-rich", "Brothy-light",
         "Soupy-thick", "Oily-rich", "Greasy-heavy", "Lean-clean", "Protein-packed", "Carb-loaded", "Gluten-light",
         "Vegan-friendly", "Vegetarian-classic", "Plant-rich",
         "Raw-fresh", "Cooked-hot", "Half-done", "Crusted", "Flaky-light", "Layered-rich", "Stuffed-full",
         "Wrapped-tight", "Dipped-sweet", "Drizzled-fine",
         "Sprinkled-light", "Powdered-soft", "Dusty-sweet", "Glazed-shiny", "Frosted-cool", "Iced-fresh",
         "Candied-sugar", "Honey-sweet", "Maple-rich", "Molten-hot",
         "Syrupy-thick", "Sugared-light", "Complex-flavor", "Simple-taste", "Minimalist-style", "Colorful-plate",
         "Vibrant-dish", "Bright-fresh", "Dark-rich", "Pale-soft",
         "Rosy-fresh", "Crimson-bold", "Scarlet-hot", "Ivory-light", "Browned-rich", "Charcoal-dark", "Smoldering-hot",
         "Refreshing-cool", "Cooling-fresh", "Hydrating-light",
         "Quenching-fresh", "Invigorating-strong", "Energizing-bright", "Soulful-rich", "Festive-bright",
         "Celebratory-joyful", "Party-style", "Picnic-ready", "Street-classic", "Casual-fresh",
         "Upscale-rich", "Affordable-light", "Budget-classic", "Family-style", "Kid-happy", "Playful-fun",
         "Cheerful-bright", "Joyful-rich", "Cozy-warm", "Inviting-fresh",
         "Welcoming-bright", "Generous-rich", "Abundant-full", "Plentiful-rich", "Overflowing-bright", "Bountiful-rich",
         "Lavish-full", "Sumptuous-rich", "Grand-classic", "Magnificent-rich"
         ]

# Generate 450 unique names
company_names = []
while len(company_names) < 5000:
    name = f"{random.choice(adjectives)} {random.choice(nouns)} "
    if name not in company_names:
        company_names.append(name)

# Save to Excel
df = pd.DataFrame({"Company Name": company_names})
df.to_excel("company_namesAll.xlsx", index=False)

print("Generated company_names.xlsx with 450 LTD company names.")
